name: Tag on csproj Version Change

on:
  push:
    branches:
      - main

permissions:
  contents: write  # ← GITHUB_TOKEN でタグを push できるようにする

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changed .csproj files
        id: csproj_changed
        run: |
          # 前のコミットがあれば使う、なければ空ツリーと比較
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            base_commit=HEAD~1
          else
            base_commit=$(git hash-object -t tree /dev/null)
          fi

          # .csproj の変更ファイルを取得
          changed=$(git diff --name-only "$base_commit" HEAD | grep '\.csproj$' || true)

          if [ -n "$changed" ]; then
            echo "csproj_changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_file=$changed" >> "$GITHUB_OUTPUT"
          else
            echo "csproj_changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Extract <Version> from .csproj
        if: steps.csproj_changed.outputs.csproj_changed == 'true'
        id: get_version
        run: |
          file=$(echo "${{ steps.csproj_changed.outputs.changed_file }}" | head -n 1)
          version=$(grep -oPm1 '(?<=<Version>)[^<]+' "$file")
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Check if tag already exists
        id: check_tag
        if: steps.get_version.outputs.version != ''
        run: |
          tag="v${{ steps.get_version.outputs.version }}"
          git fetch --tags
          if git tag | grep -qx "$tag"; then
            echo "tag_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "tag_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Git tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          version="v${{ steps.get_version.outputs.version }}"

          git tag "$version"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}" "$version"
